alma: paging::allocator::PFA Class Reference
paging::allocator::PFA Class Reference
#include <PFA.h>
Public Member Functions
PFA (const uefi::memory::map *)
void operator= (PFA &&)
void free_page (void *)
void free_pages (void *, uint64_t)
void lock_page (void *)
void lock_pages (void *, uint64_t)
void * request_page ()
size_t get_free_mem ()
size_t get_reserved_mem ()
size_t get_used_mem ()
Public Attributes
std::bitset page
Detailed Description
Page Frame Allocator class
Mantains a bitset (size of the total ammount of pages) that indicates free/used pages. You can lock a page/s or free it, you can also request a free page.
@info Requesting a free page can be improved with a free list (now it iterates from the start searching for a free page). For now it's out of scope, anyway can be easily implemented I think
Definition at line 27 of file PFA.h.
Constructor & Destructor Documentation
PFA() [1/2]
paging::allocator::PFA::PFA (const uefi::memory::map * map)
Page Frame Allocator constructor
Get the largest segment and reserves it for the PFA class (to ensure it won't run out of memory). This is quite hacky and probably in real industry this is done in other (better) way.
Then "create" the bitset (set the buffer and size). Size is calculated from UEFIMMap::get_memsize(map) (total UEFI memory). Then we divide it into page size to match 1 bit to 1 page.
Then we zero out the bitset and lock the bitset pages.
Finally we go through all the UEFI memory map to reserve unusable pages
Parameters
map UEFI memory map
Definition at line 47 of file PFA.cpp.
{
    if (map == NULL)
        return;
    efi_memory_descriptor_t *largest = PFA::get_largest_segment(map);
    size_t memsize     = get_memsize(map);
    this->free_mem     = memsize;
    this->reserved_mem = 0;
    this->used_mem     = 0;
    size_t bitset_size = memsize / kernel::page_size;
    page.set_size(bitset_size);
    page.set_buffer((uint8_t *)largest->PhysicalStart);
    PFA::zero_bitset();
    PFA::lock_pages(this->page.get_buffer(), (this->page.get_size() / (8 * kernel::page_size)) + 1);
    for (uint64_t i = 0; i < map->entries; i++) {
        efi_memory_descriptor_t *descriptor =
          (efi_memory_descriptor_t *)((uint64_t)map->map + (i * map->descriptor_size));
        if (descriptor->Type != static_cast<int>(segment_e::EFI_CONVENTIONAL_MEMORY)) {
            this->reserve_pages((void *)descriptor->PhysicalStart, descriptor->NumberOfPages);
        }
    }
}
References uefi::memory::map::descriptor_size, uefi::memory::map::entries, std::bitset::get_buffer(), lock_pages(), uefi::memory::map::map, std::bitset::set_buffer(), and std::bitset::set_size().
PFA() [2/2]
paging::allocator::PFA::PFA ()
Definition at line 17 of file PFA.cpp.
  : free_mem(0)
  , reserved_mem(0)
  , used_mem(0){};
Member Function Documentation
free_page()
void paging::allocator::PFA::free_page (void * addr)
Mark a page as free
Updates free_mem and used_mem
Definition at line 120 of file PFA.cpp.
{
    efi_physical_address_t index = (efi_physical_address_t)addr / kernel::page_size;
    /* already free page */
    if (!this->page[index])
        return;
    this->page.unset(index);
    this->free_mem += kernel::page_size;
    this->used_mem -= kernel::page_size;
}
References std::bitset::unset().
Referenced by free_pages().
free_pages()
void paging::allocator::PFA::free_pages (void * addr, uint64_t count)
Mark a number of pages as free
Updates free_mem and used_mem
Definition at line 140 of file PFA.cpp.
{
    for (uint64_t i = 0; i < count; i++)
        this->free_page((void *)((uint64_t)addr + (i * kernel::page_size)));
}
References free_page().
get_free_mem()
size_t paging::allocator::PFA::get_free_mem () inline
Gets kernel's total free memory
Definition at line 41 of file PFA.h.
    {
        return this->free_mem;
    }
get_reserved_mem()
size_t paging::allocator::PFA::get_reserved_mem () inline
Gets kernel's total reserved (UEFI, ACPI...) memory (unusable for the OS)
Definition at line 47 of file PFA.h.
    {
        return this->reserved_mem;
    }
get_used_mem()
size_t paging::allocator::PFA::get_used_mem () inline
Gets kernel's total used memory (OS's used mem, etc)
Definition at line 53 of file PFA.h.
    {
        return this->used_mem;
    }
lock_page()
void paging::allocator::PFA::lock_page (void * addr)
Mark a page as locked
Updates free_mem and used_mem
Definition at line 152 of file PFA.cpp.
{
    uint64_t index = (efi_physical_address_t)addr / kernel::page_size;
    /* already used page */
    if (this->page[index])
        return;
    this->page.set(index);
    this->free_mem -= kernel::page_size;
    this->used_mem += kernel::page_size;
}
References std::bitset::set().
Referenced by lock_pages(), and request_page().
lock_pages()
void paging::allocator::PFA::lock_pages (void * addr, uint64_t count)
Mark a number of pages as locked
Updates free_mem and used_mem
Definition at line 173 of file PFA.cpp.
{
    for (uint64_t i = 0; i < count; i++)
        this->lock_page((void *)((uint64_t)addr + (i * kernel::page_size)));
}
References lock_page().
Referenced by acpi::rsdp_v2::memmap_acpi_tables(), and PFA().
operator=()
void paging::allocator::PFA::operator= (PFA && rvalue)
Definition at line 23 of file PFA.cpp.
{
    this->free_mem     = rvalue.get_free_mem();
    this->reserved_mem = rvalue.get_reserved_mem();
    this->used_mem     = rvalue.get_used_mem();
    this->page         = static_cast<std::bitset &&>(rvalue.page);
}
request_page()
void * paging::allocator::PFA::request_page ()
Request a free page
Definition at line 249 of file PFA.cpp.
{
    for (uint64_t i = 0; i < this->page.get_size(); i++) {
        if (this->page[i])
            continue;
        /* Hack to pass the index, as lock_page(addr) gets index by addr / page_size */
        this->lock_page((void *)(i * kernel::page_size));
        return (void *)(i * kernel::page_size);
    }
    /* No memory */
    return NULL;
}
References std::bitset::get_size(), and lock_page().
Member Data Documentation
page
std::bitset paging::allocator::PFA::page
Definition at line 38 of file PFA.h.
The documentation for this class was generated from the following files:
PFA.h
PFA.cpp