alma: paging::translator::PTM Class Reference
paging::translator::PTM Class Reference
#include <PTM.h>
Public Member Functions
PTM ()
void map (uint64_t, uint64_t)
page_global_dir_entry_t * get_PGDT ()
Static Public Member Functions
static void parse (uint64_t, address_t *)
Static Public Attributes
static const uint16_t page_size = 512
Detailed Description
Page table Manager
Definition at line 129 of file PTM.h.
Constructor & Destructor Documentation
PTM()
paging::translator::PTM::PTM ()
Page table manager constructor
Just sets the PGDT to 0
Definition at line 23 of file PTM.cpp.
{
    memset(this->get_PGDT(), 0, uefi::page_size);
}
References get_PGDT(), and uefi::page_size.
Member Function Documentation
get_PGDT()
page_global_dir_entry_t * paging::translator::PTM::get_PGDT () inline
Returns the PGDT (PML4 table)
Definition at line 140 of file PTM.h.
    {
        return this->PGD_table.PGDT;
    }
Referenced by map(), and PTM().
map()
void paging::translator::PTM::map (uint64_t virt, uint64_t phys)
Map a virtual memory address to a physical memory addres using intel's x86-64 paging scheme
The table entry scheme forms a K-ary tree with the root at PGD_table (private). Each parent has 512 childrens (as each entry is 8 bytes we have 512 locations (childrens) so we get 4096 bytes of size, a page :))
The functions starts from the root of the tree, moving 1 level at a time, selecting the correct children to move to from the virtual address. Also it has to construct the children subtree if it doesn't exist.
During the function you'll see some mysterious 12 bit shifts. That's because we are going to map page aligned addresses, so it doesn't need the last 12 bits (they don't matter). We have to "remove them" when we store it on any entry as the CPU "doesn't want them" but then when WE use it we have to restore the address filling it with zeroes.
@info https://www.iaik.tugraz.at/teaching/materials/os/tutorials/paging-on-intel-x86-64/ @info http://lenovopress.com/lp1468.pdf
Get the page global entry from it's table
Get the page upper dir table from the PGD or create & link a new one if needed
Get the page upper entry from it's table
Get the page mid dir table from the PUD or create & link a new one if needed
Get the page mid entry from it's table
Get the page table dir table from the PMD or create & link a new one if needed
Get the page table entry from it's table
Fill it with the physical address
Definition at line 48 of file PTM.cpp.
{
    /* Parse uint64_t bits to a x86-64 virtual address struct */
    address_t *virtaddr = (address_t *)&virt;
    /** Get the page global entry from it's table */
    page_global_dir_entry_t *PGD = &this->get_PGDT()[virtaddr->global];
    /** Get the page upper dir table from the PGD or create & link a new one if needed */
    page_upper_dir_entry_t *PUDT;
    if (!PGD->present) {
        PUDT = (page_upper_dir_entry_t *)kernel::allocator.request_page();
        memset(PUDT, 0, uefi::page_size);
        PGD->page_ppn    = (uint64_t)PUDT >> 12;
        PGD->present     = true;
        PGD->writeable   = true;
        PGD->user_access = true;
    } else {
        PUDT = (page_upper_dir_entry_t *)((uint64_t)PGD->page_ppn << 12);
    }
    /** Get the page upper entry from it's table */
    page_upper_dir_entry_t *PUD = &PUDT[virtaddr->upper];
    /** Get the page mid dir table from the PUD or create & link a new one if needed */
    page_mid_dir_entry_t *PMDT;
    if (!PUD->present) {
        PMDT = (page_mid_dir_entry_t *)kernel::allocator.request_page();
        memset(PMDT, 0, uefi::page_size);
        PUD->page_ppn    = (uint64_t)PMDT >> 12;
        PUD->present     = true;
        PUD->writeable   = true;
        PUD->user_access = true;
    } else {
        PMDT = (page_mid_dir_entry_t *)((uint64_t)PUD->page_ppn << 12);
    }
    /** Get the page mid entry from it's table */
    page_mid_dir_entry_t *PMD = &PMDT[virtaddr->mid];
    /** Get the page table dir table from the PMD or create & link a new one if needed */
    page_table_entry_t *PTDT;
    if (!PMD->present) {
        PTDT = (page_table_entry_t *)kernel::allocator.request_page();
        memset(PTDT, 0, uefi::page_size);
        PMD->page_ppn    = (uint64_t)PTDT >> 12;
        PMD->present     = true;
        PMD->writeable   = true;
        PMD->user_access = true;
    } else {
        PTDT = (page_table_entry_t *)((uint64_t)PMD->page_ppn << 12);
    }
    /** Get the page table entry from it's table */
    page_table_entry_t *PTD = &PTDT[virtaddr->table];
    /** Fill it with the physical address */
    PTD->page_ppn    = (uint64_t)phys >> 12;
    PTD->present     = true;
    PTD->writeable   = true;
    PTD->user_access = true;
}
References get_PGDT(), and uefi::page_size.
Member Data Documentation
page_size
const uint16_t paging::translator::PTM::page_size = 512 static
Definition at line 135 of file PTM.h.
The documentation for this class was generated from the following files:
PTM.h
PTM.cpp