alma: io::PS2 Class Reference
io::PS2 Class Reference
#include <keyboard.h>
Public Member Functions
void process_scancode (uint8_t)
void delete_char (uint16_t n=1)
void add_char (char)
void add_modchar (char)
bool update ()
void scanf (char *, uint32_t)
const char * get_buffer () const
void set_buffer (char *buffer)
uint16_t get_maxsize () const
void set_maxsize (uint16_t maxsize)
Static Public Member Functions
static void enable_keyboard ()
Detailed Description
PS2 Keyboards pushes a hex keycode each time a key is pressed then another when it's released, for example:
0x1E : 'a' pressed 0x9E : 'A' released
There is no '/' por upper/lower keys, PS2 only comprehends the keys available in the keyboard, upper/lower keys do not exist on it... right?
We have to generate them by playing with pressed/released combinations
Definition at line 73 of file keyboard.h.
Member Function Documentation
add_char()
void io::PS2::add_char (char letter)
Add a new char
Definition at line 57 of file keyboard.cpp.
{
    /* Surpass buffer handling*/
    if (this->buffer_count >= PS2::buffer_maxsize) {
        switch (this->buffer_handling) {
            case PS2::buffer_mode::circular:
                this->buffer_count = 0;
                break;
            case PS2::buffer_mode::limit:
                return;
        }
    }
    this->buffer[this->buffer_count] = letter;
    this->buffer_count               = this->buffer_count + 1; // += 1 volatile deprecated
    this->has_new_key                = true;
}
Referenced by process_scancode().
add_modchar()
void io::PS2::add_modchar (char)
Add a new mod char
delete_char()
void io::PS2::delete_char (uint16_t n = 1)
Delete n chars from buffer
Definition at line 48 of file keyboard.cpp.
{
    if (n > buffer_count)
        return;
    this->buffer_count = this->buffer_count - n; // -= n volatile deprecated
    this->has_new_key  = true;
}
enable_keyboard()
void io::PS2::enable_keyboard () static
Definition at line 137 of file keyboard.cpp.
{
    kernel::idtr.add_handle(interrupts::vector_e::keyboard, interrupts::keyboard);
}
get_buffer()
const char * io::PS2::get_buffer () const inline
Returns the buffered input text
Definition at line 89 of file keyboard.h.
    {
        return this->buffer;
    };
get_maxsize()
uint16_t io::PS2::get_maxsize () const inline
Definition at line 98 of file keyboard.h.
    {
        return this->buffer_maxsize;
    };
process_scancode()
void io::PS2::process_scancode (uint8_t keycode)
Process a new scancode
Definition at line 14 of file keyboard.cpp.
{
    if (keycode < PS2_SCANCODE_SIZE) {
        char letter = PS2_SCANCODES[keycode][static_cast<int>(this->state)];
        if (letter != 0x0) {
            this->add_char(letter);
            return;
        }
    }
    switch (keycode) {
        /* L Shift */
        case 0x2a:
            this->state = PS2_State::Shifted;
            break;
        case 0xaa:
            if (this->state == PS2_State::Mayus)
                this->state = PS2_State::Normal;
            else
                this->state = PS2_State::Mayus;
            break;
        case 0xba:
            break;
        /* Del */
        case 0x0e:
            this->delete_char();
            break;
        case 0x8e:
            break;
    }
}
References add_char(), io::PS2_SCANCODE_SIZE, and io::PS2_SCANCODES.
scanf()
void io::PS2::scanf (char * buffer, uint32_t maxsize)
Read
Definition at line 84 of file keyboard.cpp.
{
    if (buffer == nullptr || maxsize <= 0)
        return;
    auto buffer_backup      = this->buffer;
    auto count_backup       = this->buffer_count;
    auto maxsize_backup     = this->buffer_maxsize;
    auto has_new_key_backup = this->has_new_key;
    auto mode_backup        = this->buffer_handling;
    this->buffer          = buffer;
    this->buffer_maxsize  = maxsize - 1;
    this->buffer_count    = 0;
    this->has_new_key     = false;
    this->buffer_handling = PS2::buffer_mode::limit;
    uint32_t last_text_size = 0;
    while (1) {
        if (kernel::keyboard.update()) {
            if (this->buffer_count > 0 && this->buffer[this->buffer_count - 1] == '\n') {
                kernel::tty.newline();
                break;
            }
            auto x_backup     = kernel::tty.get_x();
            auto y_backup     = kernel::tty.get_y();
            auto color_backup = kernel::tty.getColor();
            kernel::tty.setColor(screen::color_e::BLACK);
            for (uint32_t i = 0; i < last_text_size; i++)
                kernel::tty.printchar((char)0xdb);
            kernel::tty.set_x(x_backup);
            kernel::tty.set_y(y_backup);
            kernel::tty.setColor(color_backup);
            auto text                  = this->get_buffer();
            buffer[this->buffer_count] = '\0';
            kernel::tty.print(text);
            last_text_size = this->buffer_count;
            kernel::tty.set_x(x_backup);
            kernel::tty.set_y(y_backup);
        }
    }
    this->buffer[this->buffer_count] = '\0';
    this->buffer          = buffer_backup;
    this->buffer_maxsize  = maxsize_backup;
    this->buffer_count    = count_backup;
    this->has_new_key     = has_new_key_backup;
    this->buffer_handling = mode_backup;
}
References screen::renderer_i::getColor(), screen::renderer_i::setColor(), and update().
set_buffer()
void io::PS2::set_buffer (char * buffer) inline
Sets a new buffer to store text
Definition at line 94 of file keyboard.h.
    {
        this->buffer = buffer;
    };
set_maxsize()
void io::PS2::set_maxsize (uint16_t maxsize) inline
Definition at line 102 of file keyboard.h.
    {
        this->buffer_maxsize = maxsize;
    };
update()
bool io::PS2::update ()
True if we need to update keyboard values
Definition at line 76 of file keyboard.cpp.
{
    auto temp         = this->has_new_key;
    this->has_new_key = false;
    return temp;
}
Referenced by scanf().
The documentation for this class was generated from the following files:
keyboard.h
keyboard.cpp