alma: screen::renderer_i Class Reference
screen::renderer_i Class Reference abstract
#include <renderer.h>
Public Member Functions
void println (const char *)
void printcharln (char letter)
void print (const char *)
void printchar (char letter)
void newline ()
void clear ()
void scroll ()
virtual void draw (const char)=0
void put (const char)
void setColor (color_e)
color_e getColor ()
unsigned int get_x ()
unsigned int get_y ()
void set_x (unsigned int)
void set_y (unsigned int)
Protected Member Functions
virtual unsigned int glyph_x ()=0
virtual unsigned int glyph_y ()=0
Protected Attributes
framebuffer * fb
unsigned int x_offset
unsigned int y_offset
color_e color
Detailed Description
Interface to output to the screen
Definition at line 18 of file renderer.h.
Member Function Documentation
clear()
void screen::renderer_i::clear ()
Fast screen clear
Uses biggest integer asignations
Definition at line 100 of file renderer.cpp.
{
    uint32_t jumps = fb->buffer_size / sizeof(uint64_t);
    uint32_t rest  = fb->buffer_size % sizeof(uint64_t);
    /* Fast clear, use big integer movements */
    unsigned int i;
    for (i = 0; i < jumps; i++)
        *((uint64_t *)fb->base + i) = static_cast<uint8_t>(screen::color_e::BLACK);
    /* for sizes < 64 bytes */
    for (unsigned int j = 0; j < rest; j++)
        *((uint8_t *)((uint64_t *)fb->base + i) + j) = static_cast<uint8_t>(screen::color_e::BLACK);
    this->x_offset = 0;
    this->y_offset = 0;
}
References fb.
draw()
virtual void screen::renderer_i::draw (const char) pure virtual
Implemented in screen::psf1_renderer.
get_x()
unsigned int screen::renderer_i::get_x ()
Definition at line 157 of file renderer.cpp.
{
    return this->x_offset;
}
get_y()
unsigned int screen::renderer_i::get_y ()
Definition at line 163 of file renderer.cpp.
{
    return this->y_offset;
}
getColor()
color_e screen::renderer_i::getColor ()
Gets current color
Returns
color Color in use
Definition at line 89 of file renderer.cpp.
{
    return this->color;
}
References color.
Referenced by io::PS2::scanf().
glyph_x()
virtual unsigned int screen::renderer_i::glyph_x () protected pure virtual
renderer glyph x size
Referenced by print().
glyph_y()
virtual unsigned int screen::renderer_i::glyph_y () protected pure virtual
renderer glyph y size
Referenced by print().
newline()
void screen::renderer_i::newline () inline
Definition at line 34 of file renderer.h.
    {
        this->println("");
    };
print()
void screen::renderer_i::print (const char * str)
Print a string without default newline
Increases x_offset and y_offset, also recognises special chars as '
'
Parameters
str string to print
Definition at line 36 of file renderer.cpp.
{
    int i = 0;
    while (str[i]) {
        switch (str[i]) {
            case '\n':
                this->y_offset += this->glyph_y();
                this->x_offset = 0;
                break;
            default: {
                this->draw(str[i]);
                this->x_offset += this->glyph_x();
                if (this->x_offset >= this->fb->width)
                    this->print("\n");
            }
        }
        if ((this->y_offset + this->glyph_y()) > this->fb->height)
            this->scroll();
        i++;
    }
}
References fb, glyph_x(), glyph_y(), print(), x_offset, and y_offset.
Referenced by print(), println(), and put().
printchar()
void screen::renderer_i::printchar (char letter) inline
Definition at line 29 of file renderer.h.
    {
        char aux[] = { letter, '\0' };
        this->print(aux);
    };
printcharln()
void screen::renderer_i::printcharln (char letter) inline
Definition at line 23 of file renderer.h.
    {
        char aux[] = { letter, '\0' };
        this->println(aux);
    }
println()
void screen::renderer_i::println (const char * str)
Print a string with a default newline
Increases x_offset and y_offset, also recognises special chars as '
'
Parameters
str string to print
Definition at line 66 of file renderer.cpp.
{
    this->print(str);
    this->put('\n');
}
References print(), and put().
Referenced by acpi::rsdp_v2::print_acpi_tables().
put()
void screen::renderer_i::put (const char character)
Draw a character to the screen
Increases x_ffset and y_offset, also recognises special chars as '
'
Parameters
character Char to print
Definition at line 22 of file renderer.cpp.
{
    char aux[2] = { character, '\0' };
    this->print(aux);
}
References print().
Referenced by println().
scroll()
void screen::renderer_i::scroll ()
Definition at line 119 of file renderer.cpp.
{
    uint32_t mrg = fb->ppscl * (this->glyph_y() * 4);
    uint32_t dif = fb->buffer_size - mrg;
    uint8_t *src = (uint8_t *)fb->base + mrg;
    uint8_t *dst = (uint8_t *)fb->base;
    {
        uint32_t jumps = dif / sizeof(uint64_t);
        uint32_t rest  = dif % sizeof(uint64_t);
        unsigned int i;
        for (i = 0; i < jumps; i++)
            *((uint64_t *)dst + i) = *((uint64_t *)src + i);
        for (unsigned int j = 0; j < rest; j++)
            *((uint8_t *)((uint64_t *)dst + i) + j) = *((uint8_t *)((uint64_t *)src + i) + j);
    }
    {
        uint8_t *clr = ((uint8_t *)fb->base + fb->buffer_size) - mrg;
        uint32_t jumps = mrg / sizeof(uint64_t);
        uint32_t rest  = mrg % sizeof(uint64_t);
        unsigned int i;
        for (i = 0; i < jumps; i++)
            *((uint64_t *)clr + i) = 0;
        for (unsigned int j = 0; j < rest; j++)
            *((uint8_t *)((uint64_t *)clr + i) + j) = 0;
    }
    if (this->y_offset >= this->glyph_y())
        this->y_offset -= this->glyph_y();
}
set_x()
void screen::renderer_i::set_x (unsigned int value)
Definition at line 169 of file renderer.cpp.
{
    this->x_offset = value;
}
set_y()
void screen::renderer_i::set_y (unsigned int value)
Definition at line 175 of file renderer.cpp.
{
    this->y_offset = value;
}
setColor()
void screen::renderer_i::setColor (color_e color)
Sets a new char color to use
Parameters
color Color to use onwards
Definition at line 78 of file renderer.cpp.
{
    this->color = color;
}
References color.
Referenced by io::PS2::scanf().
Member Data Documentation
color
color_e screen::renderer_i::color protected
color of next glyph
Definition at line 61 of file renderer.h.
Referenced by screen::psf1_renderer::draw(), getColor(), screen::psf1_renderer::psf1_renderer(), and setColor().
fb
framebuffer* screen::renderer_i::fb protected
Framebuffer to use
Definition at line 51 of file renderer.h.
Referenced by clear(), screen::psf1_renderer::draw(), print(), and screen::psf1_renderer::psf1_renderer().
x_offset
unsigned int screen::renderer_i::x_offset protected
x PIXEL offset of next glyph
Definition at line 53 of file renderer.h.
Referenced by screen::psf1_renderer::draw(), print(), and screen::psf1_renderer::psf1_renderer().
y_offset
unsigned int screen::renderer_i::y_offset protected
y PIXEL offset of next glyph
Definition at line 55 of file renderer.h.
Referenced by screen::psf1_renderer::draw(), print(), and screen::psf1_renderer::psf1_renderer().
The documentation for this class was generated from the following files:
renderer.h
renderer.cpp