alma: std::bitset Class Reference
std::bitset Class Reference
#include <bitset.h>
Public Member Functions
void operator= (bitset &&)
bool operator[] (size_t)
void set (size_t)
void unset (size_t)
uint8_t * get_buffer ()
void set_buffer (uint8_t *buffer)
size_t get_size ()
void set_size (size_t size)
Detailed Description
Class that manages a imaginary array of bits
It's an array of uint8_t where you can access each bit with operator[]. Also you can set/unset bits
@info You need to provide your own buffer
Definition at line 24 of file bitset.h.
Constructor & Destructor Documentation
bitset()
std::bitset::bitset ()
Definition at line 13 of file bitset.cpp.
  : size(0)
  , buffer(nullptr)
{}
Member Function Documentation
get_buffer()
uint8_t * std::bitset::get_buffer () inline
Return buffer pointer
Definition at line 40 of file bitset.h.
    {
        return this->buffer;
    }
Referenced by paging::allocator::PFA::PFA().
get_size()
size_t std::bitset::get_size () inline
Return number of bits
Definition at line 56 of file bitset.h.
    {
        return this->size;
    }
Referenced by paging::allocator::PFA::request_page().
operator=()
void std::bitset::operator= (bitset && rvalue)
Definition at line 19 of file bitset.cpp.
{
    this->size   = rvalue.get_size();
    this->buffer = rvalue.buffer;
}
operator[]()
bool std::bitset::operator[] (size_t index)
Return the bit value of index 'index'
Parameters
index Index to look
Returns
true -> bit 1 | false -> bit 0
Definition at line 32 of file bitset.cpp.
{
    auto byte = static_cast<int>(index / 8);
    auto bit  = index % 8;
    uint8_t value = *(buffer + byte);
    return (value & (0b10000000 >> bit));
}
set()
void std::bitset::set (size_t index)
Set a bit to true
Parameters
index Index of the bit
Definition at line 48 of file bitset.cpp.
{
    auto byte = static_cast<int>(index / 8);
    auto bit  = index % 8;
    uint8_t value    = *(buffer + byte);
    uint8_t newvalue = value | (0b10000000 >> bit);
    *(buffer + byte) = newvalue;
}
Referenced by paging::allocator::PFA::lock_page().
set_buffer()
void std::bitset::set_buffer (uint8_t * buffer) inline
Set buffer pointer
Definition at line 48 of file bitset.h.
    {
        this->buffer = buffer;
    }
Referenced by paging::allocator::PFA::PFA().
set_size()
void std::bitset::set_size (size_t size) inline
Set number of bits
Warning
Not used to check correct access
Definition at line 66 of file bitset.h.
    {
        this->size = size;
    }
Referenced by paging::allocator::PFA::PFA().
unset()
void std::bitset::unset (size_t index)
Set a bit to false
Parameters
index Index of the bit
Definition at line 65 of file bitset.cpp.
{
    auto byte = static_cast<int>(index / 8);
    auto bit  = index % 8;
    uint8_t value    = *(buffer + byte);
    uint8_t newvalue = value & ~(0b10000000 >> bit);
    *(buffer + byte) = newvalue;
}
Referenced by paging::allocator::PFA::free_page().
The documentation for this class was generated from the following files:
bitset.h
bitset.cpp